name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "_posts/**"
      - "_layouts/**"
      - "assets/**"
      - "*.html"
      - "*.md"
      - "_config.yml"
      - ".github/workflows/deploy.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create assets/js directory if not exists
        run: mkdir -p assets/js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
